  CREATE TABLE tabla1 (
	A VARCHAR(20) PRIMARY KEY,
  	B VARCHAR(20)
);

CREATE TABLE tabla3 (
	C VARCHAR(20),
  	D INTEGER,
  	E VARCHAR(20),
  	PRIMARY KEY (C,D)
);

CREATE TABLE tabla2 (
	A VARCHAR(20),
  	C VARCHAR(20),
  	D INTEGER,
  	PRIMARY KEY(A,C,D),
  	CONSTRAINT fk_A
  		FOREIGN KEY (A)
  			REFERENCES tabla1(A),
	CONSTRAINT fk_CD
  		FOREIGN KEY (C,D)
  			REFERENCES tabla3(C,D)
);